package com.pizzeria.MammaMia.Enums;

public enum CategoryType {
    BRASILEIRA, ITALIANA, JAPONESA, CHINESA, FAST_FOOD, VEGETARIANA, VEGANA, SOBREMESAS, LANCHES, PIZZA, MARISQUEIRA, PADARIA, CAFETERIA, MEXICANA, BEBIDA
}
